### ISSUE TITLE
Toggling "Include browser polyfill" should refresh the current editor(s)?

### ISSUE THREAD

**Issue by ericlaw1979** [oliverdunk/web-extension-playground#1]
...such that `chrome.` becomes `browser.` immediately instead of requiring the user to switch browsers/templates first?

**Comment by oliverdunk** [comment]
Thanks for the feedback! I think that probably makes sense as a change since it would be consistent with the other settings.

On a side note, I’m still slightly unsure about the nicest way for all of the setting changes to behave. For example, if you’ve written code, is it helpful to revert your changes or just silently include the polyfill?

Perhaps I just need a better modal in this situation with both “Keep code” and “Reset template” as options.

**Comment by oliverdunk** [comment]
This should be fixed now! Thanks again.
